#!/usr/bin/env bun
/**
 * Embed the runtime assets so `--compile` produces a genuinely single binary.
 *
 * pi discovers skills and themes from directories on disk, and a compiled Bun
 * binary has no directories. So the asset tree is baked into a generated module
 * here and unpacked into the agent dir at startup (see unpackAssets in main.ts).
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = import.meta.dir;
const TREES = ["skills", "themes"];
const FILES = ["orqi-system-prompt.txt"];

function walk(dir: string): string[] {
	return readdirSync(dir).flatMap((entry) => {
		const path = join(dir, entry);
		return statSync(path).isDirectory() ? walk(path) : [path];
	});
}

const assets: Record<string, string> = {};
for (const tree of TREES) {
	for (const path of walk(join(ROOT, tree))) {
		assets[relative(ROOT, path)] = readFileSync(path, "utf8");
	}
}
for (const file of FILES) {
	assets[file] = readFileSync(join(ROOT, file), "utf8");
}

// Content hash doubles as the unpack directory name, so a rebuilt binary
// unpacks afresh and an unchanged one reuses what is already on disk.
const hash = Bun.hash(JSON.stringify(assets)).toString(16);

writeFileSync(
	join(ROOT, "src", "assets.generated.ts"),
	`// Generated by build.ts. Do not edit.\nexport const HASH = ${JSON.stringify(hash)};\nexport const ASSETS: Record<string, string> = ${JSON.stringify(assets)};\n`,
);

console.log(`embedded ${Object.keys(assets).length} files (${hash})`);
